### ISSUE TITLE
Not working for assemblies built in release mode and comparing the same assembly built in debug mode.

### ISSUE THREAD

**Issue by RahulKumarSharma24** [stucampbell/AssemblyComparer#3]
Not working for assemblies built in release mode and comparing the same assembly built in debug mode.

**Comment by stucampbell** [comment]
That makes sense. You wouldn't expect the debug IL to be the same as the release IL.

**Comment by RahulKumarSharma24** [comment]
I wrote the almost same program(was using SHA256 to calculate hash) and want to compare assemblies, not able to find a way to say that debug assembly and release assembly was built from same code base, still searching this. Is there any way to verify this?
